/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.LeTan;

import Dao.DichVuDAO;
import Dao.HoaDonDAO;
import Dao.NhanVienDAO;
import Helper.JDBCHelper;
import Helper.MsgBox;
import Helper.XDate;
import Model.DichVu;
import Model.HoaDon;
import Model.NhanVien;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nhatd
 */
public class DoiLich extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    List<Model.DichVu> ls = new ArrayList<>();
    NhanVienDAO nvdao=new NhanVienDAO();
    DichVuDAO dvdao=new DichVuDAO();
    HoaDonDAO hddao=new HoaDonDAO();
    public DoiLich(String contructor) {
        initComponents();
        txtId_HD.setText(contructor);
        init();
    }
    
    void init(){
        fillComboThoCat();
        setNgay();
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboThoiGian.getModel();
        mol.removeAllElements();
        fillComboThoiGian();
//        fillComboboxDichVu();
        
    }
    
//    private void fillComboboxDichVu() {
//        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboDichVu.getModel();
//        mol.removeAllElements();
//        List<Model.DichVu> list = dvdao.selectAll();
//        for (Model.DichVu dv : list) {
//            mol.addElement(dv);
//        }
//    }
    
    private void fillComboThoCat() {
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboThoCat.getModel();
        mol.removeAllElements();
        List<NhanVien> list = nvdao.selectByThoCat();
        for (NhanVien nv : list) {
            mol.addElement(nv);
        }
    }
    
    private void fillComboThoiGian() {
        cboThoiGian.removeAllItems();
        Time tm = new Time(8, 0);
        cboThoiGian.addItem(tm.toString());
        for (int i = 0; true; i++) {
            tm.tangPhut();
            cboThoiGian.addItem(tm.toString());
            if (tm.toString().equals("18:00")) {
                return;
            }
        }
    }

    
    private void setNgay() {
        this.cboNgayDat.removeAllItems();
        this.cboNgayDat.addItem("Chọn ngày");
        SimpleDateFormat sdf = new SimpleDateFormat("E, dd-MM-yyyy");
        java.util.Date now = new java.util.Date();
        String date = sdf.format(now);
        Calendar cal = Calendar.getInstance();
        for (int i = 0; i < 7; i++) {
            if (i == 0) {
                cal.add(Calendar.DAY_OF_WEEK, +0);
                this.cboNgayDat.addItem(sdf.format(cal.getTime()));
            }
            cal.add(Calendar.DAY_OF_WEEK, +1);
            this.cboNgayDat.addItem(sdf.format(cal.getTime()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId_HD = new javax.swing.JTextField();
        txtId_NV = new javax.swing.JTextField();
        txtID_KH = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtDatCoc = new javax.swing.JTextField();
        txtThanToan = new javax.swing.JTextField();
        txtDanhGia = new javax.swing.JTextField();
        txtTrangThaiTT = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        txtGioHen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        cboThoCat = new javax.swing.JComboBox<>();
        cboNgayDat = new javax.swing.JComboBox<>();
        cboThoiGian = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHDCT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/receipt.png"))); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        btnsua.setText("Đổi lịch");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        cboThoCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNgayDat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Tên dịch vụ", "Giá tiền"
            }
        ));
        tblHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHDCT);

        jLabel1.setText("Ngày đặt:");

        jLabel2.setText("Thợ cắt");

        jLabel4.setText("Giờ hẹn:");

        jLabel5.setText("Mã lịch đặt:");

        jLabel6.setText("Đặt cọc:");

        jLabel7.setText("Trạng thái:");

        jLabel8.setText("Trạng thái thanh toán:");

        jLabel9.setText("Tổng tiền:");

        jLabel10.setText("Ngày tạo:");

        jLabel11.setText("Mã khách hàng:");

        jLabel12.setText("Phản hồi:");

        jLabel13.setText("Mã nhân viên:");

        jLabel16.setText("Đánh giá:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboNgayDat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboThoiGian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboThoCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(txtId_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                                .addComponent(btnsua)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)
                                                .addGap(8, 8, 8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(txtDanhGia)))))
                                    .addComponent(txtGioHen))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtID_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNgayTao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                                .addComponent(txtThanToan, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTrangThaiTT)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDatCoc)
                                            .addComponent(txtId_HD)))))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2))
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrangThaiTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(txtDatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(cboThoCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtThanToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId_NV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGioHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(btnsua)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtID_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))))
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id=txtId_HD.getText();       
        HoaDonDAO hddao=new HoaDonDAO();      
        Model.HoaDon hd=hddao.selectById(id);
        String sql = "select*from HoaDon where Id=" + id;
        ResultSet rs=JDBCHelper.query(sql);
        try {
            while (rs.next()) {                
                Object[]item=new Object[13];
                item[0]=rs.getInt("Id");
                item[1]=rs.getInt("Id_KH");
                item[2]=rs.getInt("Id_NV");
                item[3]=rs.getInt("Id_TC");
                item[4]=rs.getString("NgayHen");
                item[5]=rs.getString("NgayTao");
                item[6]=rs.getString("DatCoc");
                item[7]=rs.getString("ThanhToan");
                item[8]=rs.getString("DanhGia");
                item[9]=rs.getString("PhanHoi");
                item[10]=rs.getString("TrangThaiTT");
                item[11]=rs.getString("TrangThai");
                item[12]=rs.getString("GioHen");
                txtID_KH.setText(item[1].toString());
                txtId_NV.setText(item[2].toString());
                cboNgayDat.setSelectedItem(item[4].toString());
                txtNgayTao.setText(item[5].toString());
                txtDatCoc.setText(item[6].toString());
                txtThanToan.setText(item[7].toString());
                txtDanhGia.setText(item[8].toString());
                txtTrangThaiTT.setText(item[10].toString());
                txtTrangThai.setText(item[11].toString());
                cboThoiGian.setSelectedItem(item[12].toString());
            }
        } catch (Exception e) {
        }
        
        String sql1 ="select*from HoaDonChiTiet join DichVu on HoaDonChiTiet.Id_DV=DichVu.Id where Id_HD="+id;
        ResultSet rs1=JDBCHelper.query(sql1);
        DefaultTableModel model =(DefaultTableModel)tblHDCT.getModel();
        model.setRowCount(0);
        try {
            while (rs1.next()){                
                Object[]item=new Object[3];
                item[0]=rs1.getString("Id");
                item[1]=rs1.getString("TenDV");
                item[2]=rs1.getString("GiaTien");
                model.addRow(item);
            }
            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    Model.HoaDon getForm() throws ParseException{
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboThoCat.getModel();
        NhanVien nv = (NhanVien) mol.getSelectedItem();
        Model.HoaDon hd=new HoaDon();
        int ThoiGian = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date ngayTao = new java.util.Date();
        String ngay = sdf.format(ngayTao);
        String ngayhen = (String) cboNgayDat.getSelectedItem();
        String[] parts = ngayhen.split(",");
        String part = parts[1];
        java.util.Date NgayHen = sdf.parse(part);
        System.out.println(sdf.format(NgayHen));
        String gioHen = (String) cboThoiGian.getSelectedItem();
        Time tm = new Time(gioHen);
        tm.CongThoiGian(ThoiGian);
        hd.setId(Integer.valueOf(txtId_HD.getText()));
        hd.setId_KH(Integer.valueOf(txtID_KH.getText()));
        hd.setId_NV(Integer.valueOf(txtId_NV.getText()));
        hd.setId_TC(nv.getId());
        hd.setNgayHen(sdf.parse(part));
        hd.setGioKetThuc(tm.toString());
        hd.setNgayTao(Date.valueOf(txtNgayTao.getText()));
        hd.setDatCoc(Integer.valueOf(txtDatCoc.getText()));
        hd.setThanhToan(Integer.valueOf(txtDatCoc.getText()));
        hd.setDanhGia(txtDanhGia.getText());
        hd.setPhanHoi(null);
        hd.setTrangThaiTT(txtTrangThaiTT.getText());
        hd.setTrangThai(txtTrangThai.getText());
       
        hd.setGioHen(gioHen);
        return hd;
    }
    
     private boolean ValidateFrom() {
        if (cboNgayDat.getSelectedItem().equals("Chọn ngày")) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn ngày đặt", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
     
     
    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel mol2 = (DefaultComboBoxModel) cboThoCat.getModel();
        NhanVien nv1 = (NhanVien) mol2.getSelectedItem();
        if (this.ValidateFrom() == true) {
            try {
                Model.HoaDon hd = getForm();                
                String sql1 ="select Id_TC,NgayHen,GioHen from HoaDon";
                ResultSet rs3=JDBCHelper.query(sql1);
                try {
                    while (rs3.next()) {                        
                        Object[]item=new Object[3];
                        item[0]=rs3.getInt("Id_TC");
                        item[1]=rs3.getString("NgayHen");
                        item[2]=rs3.getString("GioHen");                                              
                        int maTC=Integer.valueOf(item[0].toString());
                        String ngayHenHD=XDate.toString(hd.getNgayHen(),"yyyy-MM-dd");
                        if (hd.getId_TC().equals(maTC)&&ngayHenHD.equals(item[1].toString())&&hd.getGioHen().equals(item[2].toString())) {
                        JOptionPane.showMessageDialog(this, "Lịch này đã có người đặt rồi nhá!");
                        return;
                       }
                    }                                
                    try {
                        String ngayhen = (String) cboNgayDat.getSelectedItem();
                        String[] parts = ngayhen.split(",");
                        String part = parts[1];
                        System.out.println("Ngày hẹn:"+part);
                        String gioHen =(String)cboThoiGian.getSelectedItem();
                         String[] parts1 = gioHen.split(":");
                          String parts2 = parts1[0];
                          System.out.println("Giờ hẹn:"+parts2);
                        hddao.update(hd);
                        MsgBox.alert(this, "Đổi lịch thành công");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                
                } catch (Exception e) {
                }
            } catch (ParseException ex) {
                Logger.getLogger(DoiLich.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tblHDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDCTMouseClicked
        // TODO add your handling code here:
//        int row=tblHDCT.getSelectedRow();
//        txtMaHDCT.setText(tblHDCT.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblHDCTMouseClicked

//    private void kiemTra() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDichVu.getModel();
//        Model.DichVu cbodv = (Model.DichVu) model.getSelectedItem();
//            for (int i = 0; i < ls.size(); i++) {
//                System.out.println("dv:" + ls.get(i));
//                if (ls.get(i).equals(cbodv)) {
//                    JOptionPane.showMessageDialog(this, "Dịch vụ này đã được thêm vào rồi!");
//                    return;
//                }
//            }
//            ls.add(cbodv);            
//            fillTable1();
//    }
    
//     private void fillTable1() {
//        DefaultTableModel mol = (DefaultTableModel) tblHDCT.getModel();
//        mol.setRowCount(0);
//        try {
//            Model.DichVu dichVu = (Model.DichVu) cboDichVu.getSelectedItem();
//            for (Model.DichVu dv : ls) {
//                Object[] row = {
//                    dv.getId(), dv.getTenDV(), dv.getGiaTien()
//                };
//                mol.addRow(row);
//            }
//        } catch (Exception e) {
//        }
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JComboBox<String> cboNgayDat;
    private javax.swing.JComboBox<String> cboThoCat;
    private javax.swing.JComboBox<String> cboThoiGian;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHDCT;
    private javax.swing.JTextField txtDanhGia;
    private javax.swing.JTextField txtDatCoc;
    private javax.swing.JTextField txtGioHen;
    private javax.swing.JTextField txtID_KH;
    private javax.swing.JTextField txtId_HD;
    private javax.swing.JTextField txtId_NV;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtThanToan;
    private javax.swing.JTextField txtTrangThai;
    private javax.swing.JTextField txtTrangThaiTT;
    // End of variables declaration//GEN-END:variables
}
