/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.ChucNang;

import Dao.DichVuDAO;
import Dao.HoaDonDAO;
import Dao.NhanVienDAO;
import Helper.JDBCHelper;
import Helper.MsgBox;
import Helper.XDate;
import Model.DichVu;
import Model.HoaDon;
import Model.NhanVien;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import UI.LeTan.Time;

/**
 *
 * @author nhatd
 */
public class DoiLich extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    List<Model.DichVu> ls = new ArrayList<>();
    NhanVienDAO nvdao = new NhanVienDAO();
    DichVuDAO dvdao = new DichVuDAO();
    HoaDonDAO hddao = new HoaDonDAO();

    public DoiLich(String contructor) {
        initComponents();
        txtId_HD.setText(contructor);
        init();
    }

    void init() {
        fillComboThoCat();
        setNgay();
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboThoiGian.getModel();
        mol.removeAllElements();

    }


    private void fillComboThoCat() {
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboThoCat.getModel();
        mol.removeAllElements();
        List<NhanVien> list = nvdao.selectByThoCat();
        for (NhanVien nv : list) {
            mol.addElement(nv);
        }
    }

    private void fillComboThoiGian() {
        cboThoiGian.removeAllItems();
        String gioHenB = (String) lblGioHen.getText();
        String[] chuoi = gioHenB.split(":");
        String tiep = chuoi[0];
        String chuoiPhut1 = chuoi[1];
        Integer chuoiPhut = Integer.valueOf(chuoiPhut1);
        System.out.println("chuỗi phút:" + chuoiPhut);
        Integer gioHenDB = Integer.valueOf(tiep);
        System.out.println("Giờ hẹn trong database:" + gioHenDB);
        System.out.println("--------------------------------");

        if (chuoiPhut1.equals("00")) {
            cboThoiGian.addItem("8:00");
            cboThoiGian.addItem("9:00");
            cboThoiGian.addItem("10:00");
            cboThoiGian.addItem("11:00");
            cboThoiGian.addItem("12:00");
            cboThoiGian.addItem("13:00");
            cboThoiGian.addItem("14:00");
            cboThoiGian.addItem("15:00");
            cboThoiGian.addItem("16:00");
            cboThoiGian.addItem("17:00");
            cboThoiGian.addItem("18:00");
        } else {
            cboThoiGian.addItem("8:30");
            cboThoiGian.addItem("9:30");
            cboThoiGian.addItem("10:30");
            cboThoiGian.addItem("11:30");
            cboThoiGian.addItem("12:30");
            cboThoiGian.addItem("13:30");
            cboThoiGian.addItem("14:30");
            cboThoiGian.addItem("15:30");
            cboThoiGian.addItem("16:30");
            cboThoiGian.addItem("17:30");
        }

    }

    private void setNgay() {
        this.cboNgayDat.removeAllItems();
        this.cboNgayDat.addItem("Chọn ngày");
        SimpleDateFormat sdf = new SimpleDateFormat("E, dd-MM-yyyy");
        java.util.Date now = new java.util.Date();
        String date = sdf.format(now);
        Calendar cal = Calendar.getInstance();
        for (int i = 0; i < 7; i++) {
            if (i == 0) {
                cal.add(Calendar.DAY_OF_WEEK, +0);
                this.cboNgayDat.addItem(sdf.format(cal.getTime()));
            }
            cal.add(Calendar.DAY_OF_WEEK, +1);
            this.cboNgayDat.addItem(sdf.format(cal.getTime()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId_HD = new javax.swing.JTextField();
        txtNgayHen = new javax.swing.JTextField();
        txtMaTC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        cboThoCat = new javax.swing.JComboBox<>();
        cboNgayDat = new javax.swing.JComboBox<>();
        cboThoiGian = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGioKT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblGioHen = new javax.swing.JTextField();

        setClosable(true);

        txtId_HD.setEditable(false);

        txtNgayHen.setEditable(false);

        txtMaTC.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/receipt.png"))); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        btnsua.setText("Đổi lịch");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        cboThoCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNgayDat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Ngày đặt:");

        jLabel2.setText("Thợ cắt");

        jLabel4.setText("Giờ hẹn:");

        jLabel5.setText("Mã lịch đặt:");

        jLabel12.setText("Mã thợ cắt");

        jLabel16.setText("Ngày Hẹn");

        jLabel3.setText("Giờ KT:");

        txtGioKT.setEditable(false);

        jLabel6.setText("Giờ hẹn:");

        lblGioHen.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblGioHen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(cboThoiGian, 0, 235, Short.MAX_VALUE)
                            .addComponent(cboNgayDat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboThoCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtGioKT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(txtId_HD, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jLabel16)
                            .addComponent(txtMaTC)
                            .addComponent(txtNgayHen))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(btnsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboThoCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGioKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua)
                    .addComponent(jButton1))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String id = txtId_HD.getText();
        HoaDonDAO hddao = new HoaDonDAO();
        Model.HoaDon hd = hddao.selectById(id);
        String sql = "select*from HoaDon where Id=" + id;
        ResultSet rs = JDBCHelper.query(sql);
        try {
            while (rs.next()) {
                Object[] item = new Object[14];
                item[0] = rs.getInt("Id");
                item[1] = rs.getInt("Id_KH");
                item[2] = rs.getInt("Id_NV");
                item[3] = rs.getInt("Id_TC");
                item[4] = rs.getString("NgayHen");
                item[5] = rs.getString("NgayTao");
                item[6] = rs.getString("DatCoc");
                item[7] = rs.getString("ThanhToan");
                item[8] = rs.getString("DanhGia");
                item[9] = rs.getString("PhanHoi");
                item[10] = rs.getString("TrangThaiTT");
                item[11] = rs.getString("TrangThai");
                item[12] = rs.getString("GioHen");
                item[13] = rs.getString("GioKT");
                txtNgayHen.setText(item[4].toString());
                lblGioHen.setText(item[12].toString());
                txtGioKT.setText(item[13].toString());
                txtMaTC.setText(item[3].toString());

            }
        } catch (Exception e) {
        }
        fillComboThoiGian();

    }//GEN-LAST:event_jButton1ActionPerformed

    Model.HoaDon getForm() throws ParseException {
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboThoCat.getModel();
        NhanVien nv = (NhanVien) mol.getSelectedItem();
        Model.HoaDon hd = new HoaDon();
        int ThoiGian = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date ngayTao = new java.util.Date();
        String ngay = sdf.format(ngayTao);
        String ngayhen = (String) cboNgayDat.getSelectedItem();
        String[] parts = ngayhen.split(",");
        String part = parts[1];
        java.util.Date NgayHen = sdf.parse(part);
        System.out.println(sdf.format(NgayHen));
        String gioHen = (String) cboThoiGian.getSelectedItem();
        Time tm = new Time(gioHen);
        tm.CongThoiGian(ThoiGian);
        hd.setId(Integer.valueOf(txtId_HD.getText()));
        hd.setId_KH(0);
        hd.setId_NV(0);
        hd.setId_TC(nv.getId());
        hd.setNgayHen(sdf.parse(part));
        hd.setGioKetThuc(tm.toString());
        hd.setNgayTao(null);
        hd.setDatCoc(0);
        hd.setThanhToan(0);
        hd.setDanhGia(null);
        hd.setPhanHoi(null);
        hd.setTrangThaiTT(null);
        hd.setTrangThai(null);
        hd.setGioKetThuc(txtGioKT.getText());
        hd.setGioHen(gioHen);
        return hd;
    }

    private boolean ValidateFrom() {
        if (cboNgayDat.getSelectedItem().equals("Chọn ngày")) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn ngày đặt", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    public boolean SoSanh(String bd, String kt, String chon) {
        String giobd[] = bd.split(":");
        int bdg = Integer.valueOf(giobd[0]);
        int bdp = Integer.valueOf(giobd[1]);
        String giokt[] = kt.split(":");
        int ktg = Integer.valueOf(giokt[0]);
        int ktp = Integer.valueOf(giokt[1]);
        String chong[] = chon.split(":");
        int chonh = Integer.valueOf(chong[0]);
        int chonp = Integer.valueOf(chong[1]);

        if (chonh > bdg && chonh < ktg) {
            return false;
        } else if (ktg == chonh) {
            if (ktp > chonp) {
                return false;
            } else {
                return true;
            }
        } else if (bdg == chonh) {
            if (bdp <= chonp) {
                return false;
            } else {
                return true;
            }
        } else {
            return true;
        }
    }


    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        String gioKT_ID;

        DefaultComboBoxModel mol2 = (DefaultComboBoxModel) cboThoCat.getModel();
        NhanVien nv1 = (NhanVien) mol2.getSelectedItem();
        if (this.ValidateFrom() == true) {
            try {
                Model.HoaDon hd = getForm();
                List<HoaDon> list = hddao.SelectHoaDonByNgay(hd);
                String sql1 = "select Id_TC,NgayHen,GioHen from HoaDon";
                ResultSet rs3 = JDBCHelper.query(sql1);
                try {
                    while (rs3.next()) {
                        Object[] item = new Object[3];
                        item[0] = rs3.getInt("Id_TC");
                        item[1] = rs3.getString("NgayHen");
                        item[2] = rs3.getString("GioHen");
                        int maTC = Integer.valueOf(item[0].toString());
                        String ngayHenHD = XDate.toString(hd.getNgayHen(), "yyyy-MM-dd");
                        if (hd.getId_TC().equals(maTC) && ngayHenHD.equals(item[1].toString()) && hd.getGioHen().equals(item[2].toString())) {
                           
                            for (Model.HoaDon hoaDon : list) {
                                if (this.SoSanh(hoaDon.getGioHen(), hoaDon.getGioKetThuc(), hd.getGioHen()) == false) {
                                   MsgBox.alert(this, "Lịch này có người đặt rồi nhá!");
                                    return;
                                }
                            }

                        }

                    }
                    try {
                        String gioHen = (String) cboThoiGian.getSelectedItem();
                        String[] parts1 = gioHen.split(":");
                        String parts2 = parts1[0];
                        String chuoiCB1 = parts1[1];
                        Integer chuoiCB = Integer.valueOf(chuoiCB1);
                        System.out.println("Giờ hẹn:" + parts2);
                        Integer gioHen2 = Integer.valueOf(parts2);
                        System.out.println("---------");

                        String gioHenB = (String) lblGioHen.getText();
                        String[] chuoi = gioHenB.split(":");
                        String tiep = chuoi[0];
                        String chuoiPhut1 = chuoi[1];
                        Integer chuoiPhut = Integer.valueOf(chuoiPhut1);
                        System.out.println("chuỗi phút:" + chuoiPhut);
                        Integer gioHenDB = Integer.valueOf(tiep);
                        System.out.println("Giờ hẹn trong database:" + gioHenDB);
                        System.out.println("--------------------------------");

                        String gioHenKT = (String) txtGioKT.getText();
                        String[] chuoi1 = gioHenKT.split(":");
                        String tiep1 = chuoi1[0];
                        Integer gioKTDB = Integer.valueOf(tiep1);
                        System.out.println("Giờ kt trong database" + gioKTDB);
                        System.out.println("***********************");
                        System.out.println("check ngày hẹn:");
                        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                        String ngayhen = (String) cboNgayDat.getSelectedItem();
                        String[] parts = ngayhen.split(",");
                        String part = parts[1];
                        java.util.Date NgayHen = sdf.parse(part);
                        System.out.println("*****" + sdf.format(NgayHen) + "****");
                        String ngayDB = String.valueOf(NgayHen);

                        String ngayParst = txtNgayHen.getText();
                        java.util.Date date = sdf.parse(ngayParst);

                        System.out.println("ngày:" + sdf.format(date));
                        //giờ chọn bằng giờ ban đầu
                        String b = txtNgayHen.getText();

                        //giờ hẹn tăng thêm 1 tiếng,giờ hẹn giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 1) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 1 tiếng,giờ hẹn giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+1)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+1)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }

                            KiemTra(hd);
                        }
                        //giờ hẹn tăng thêm 2 tiếng,giờ hẹn nhỏ hơn  10 giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 2) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "//giờ hẹn tăng thêm 2 tiếng,giờ hẹn nhỏ hơn  10 giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+2)))+CONVERT(nvarchar,right(GioHen,3)) ,Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+2)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 2 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 2)) {
                            MsgBox.alert(this, "Giờ hẹn tăng thêm 2 tiếng,Giờ hẹn nhỏ hơn 10 và giơ kết thúc lớn hơn = 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+2)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+2)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 2 tiếng,giờ hẹn lớn hơn = 10 và giờ kết thúc lớn hơn =10
                        if (gioHenDB >= 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 2)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 2 tiếng,giờ hẹn lớn hơn= 10 và giờ kết thúc lớn hơn =10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+2)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+2)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 3 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 3) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 3 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+3)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+3)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 3 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn bằng 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 3)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 3 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn bằng 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+3)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+3)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn tăng thêm 3 tiếng,giờ hẹn lớn hơn=10 và giờ kết thúc lớn hơn=10
                        if (gioHenDB >= 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 3)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 3 tiếng,giờ hẹn lớn hơn=10 và giờ kết thúc lớn hơn=10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+3)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+3)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 4 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 4) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 4 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+4)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+4)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 4 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 4)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 4 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+4)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+4)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }
                        //giờ hẹn tăng thêm 4 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB + 4) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 4 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+4)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+4)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 5 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 5) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 5 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+5)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+5)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 5 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 4)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 5 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+5)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+5)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }
                        //giờ hẹn tăng thêm 5 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB + 5) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 5 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+5)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+5)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn tăng thêm 6 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 6) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 6 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+6)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+6)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 6 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 6)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 6 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+6)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+6)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn tăng thêm 6 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB + 6) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 6 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+6)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+6)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn tăng thêm 7 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 7) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 7 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+7)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+7)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 7 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 7)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 7 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+7)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+7)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn tăng thêm 7 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB + 7) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 7 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+7)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+7)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn tăng thêm 8 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB + 8) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 8 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+8)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)+8)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 8 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 8)) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 8 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+8)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+8)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn tăng thêm 8 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB + 8) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 8 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+8)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+8)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

//                          //giờ hẹn  tăng thêm 1 tiếng,giờ hẹn nhỏ hơn 10h và giờ kết thúc lớn hơn 10h
//                          if(gioHenDB<10&&gioKTDB>=10&&gioHen2==(gioHenDB+1)){
//                              MsgBox.alert(this, "Giờ hẹn nhỏ hơn 10 và giơ kết thúc lớn hơn = 10");
//                              String sql3="update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+1)))+CONVERT(nvarchar,right(GioHen,3)) where Id="+txtId_HD.getText();
//                              String sql4="update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+1)))+CONVERT(nvarchar,right(GioKT,3)) where Id ="+txtId_HD.getText();
//                                try {
//                                  JDBCHelper.update(sql3);
//                                  JDBCHelper.update(sql4);
//                              } catch (Exception e) {
//                              }
//                                
//                          }
                        ////giờ hẹn giảm
                        //giờ hẹn giảm 1 tiếng,giờ hẹn giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 1) && gioHen2 < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm 1 tiếng,giờ hẹn giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-1)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-1)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }

                            KiemTra(hd);
                        }
                        //giờ hẹn giảm 1 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB - 1) && gioHenDB < 10 && gioKTDB >= 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "//giờ hẹn  giảm 1 tiếng,giờ hẹn nhỏ hơn  10 giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-1)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-1)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm 1 tiếng,giờ hẹn và giờ kết thúc lớn hơn 10
                        if (gioHenDB >= 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 1)) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 1 tiếng,giờ hẹn lớn hơn= 10 và giờ kết thúc lớn hơn =10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-1)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-1)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm 2 tiếng,giờ hẹn nhỏ hơn  10 giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 2) && gioHenDB < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "//giờ hẹn  giảm 2 tiếng,giờ hẹn nhỏ hơn  10 giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-2)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-2)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 2 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 2) && gioHenDB >= 8) {
                            MsgBox.alert(this, "Giờ hẹn giảm thêm 2 tiếng,Giờ hẹn nhỏ hơn 10 và giơ kết thúc lớn hơn = 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-2)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-2)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 2 tiếng,giờ hẹn lớn hơn = 10 và giờ kết thúc lớn hơn =10
                        if (gioHenDB >= 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 2)) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 2 tiếng,giờ hẹn lớn hơn= 10 và giờ kết thúc lớn hơn =10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-2)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-2)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 3 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 3) && gioHenDB < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 3 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-3)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-3)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn tăng thêm 3 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn bằng 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 3) && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 3 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn bằng 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-3)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-3)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn giảm thêm 3 tiếng,giờ hẹn lớn hơn=10 và giờ kết thúc lớn hơn=10
                        if (gioHenDB >= 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 3)) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 3 tiếng,giờ hẹn lớn hơn=10 và giờ kết thúc lớn hơn=10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-3)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-3)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn  giảm 4 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 4) && gioHenDB < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 4 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-4)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-4)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 4 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 4) && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 4 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-4)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-4)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }
                        //giờ hẹn giảm thêm 4 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB - 4) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 4 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-4)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-4)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 5 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 5) && gioHenDB < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 5 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-5)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-5)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 5 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 5) && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 5 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-5)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-5)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }
                        //giờ hẹn giảm thêm 5 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB - 5) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn tăng thêm 5 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-5)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-5)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn giảm thêm 6 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 6) && gioHenDB < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 6 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-6)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-6)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 6 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 6) && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 6 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-6)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-6)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn giảm thêm 6 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB - 6) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 6 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-6)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-6)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn giảm thêm 7 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 7) && gioHenDB < 10 && gioKTDB < 10 && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 7 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-7)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-7)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 7 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 7) && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 7 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-7)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-7)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn giảm thêm 7 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB - 7) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 7 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-7)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-7)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn giảm thêm 8 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc nhỏ hơn 10
                        if (gioHen2 == (gioHenDB - 8) && gioHenDB < 10 && gioKTDB < 10) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 8 tiếng,giờ hẹn hỏ hơn 10 và giờ kết thúc nhỏ hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-8)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,1)-8)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                        //giờ hẹn giảm thêm 8 tiếng,giờ hẹn nhỏ hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB - 8) && gioHenDB >= 8) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 8 tiếng,giờ hẹn nhỏ hơn 10,giờ kết thúc lớn hơn 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)-8)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-8)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }
                        //giờ hẹn giảm thêm 8 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB - 8) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "giờ hẹn giảm thêm 8 tiếng,giờ hẹn lớn hơn 10 và giờ kết thúc lớn hơn 10");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)-8)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)-8)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn  tăng thêm 1 tiếng,giờ hẹn nhỏ hơn 10h và giờ kết thúc lớn hơn 10h
                        if (gioHenDB < 10 && gioKTDB >= 10 && gioHen2 == (gioHenDB + 1)) {
                            MsgBox.alert(this, "Tăng 1 tiếng,Giờ hẹn nhỏ hơn 10 và giơ kết thúc lớn hơn = 10");
                            String sql3 = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,1)+1)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String sql4 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+1)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + txtId_HD.getText();
                            try {
                                JDBCHelper.update(sql3);
                                JDBCHelper.update(sql4);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);

                        }

                        //giờ hẹn tăng thêm 1 tiếng,giờ hẹn và giờ kết thúc lớn hơn 10
                        if (gioHen2 == (gioHenDB + 1) && gioHenDB >= 10 && gioKTDB >= 10) {
                            MsgBox.alert(this, "tăng 1 tiếng,Giờ hẹn lớn hơn =10 và tăng thêm 1 tiếng");
                            String sql = "update HoaDon set GioHen=convert(nvarchar,(CONVERT(int,left(GioHen,2)+1)))+CONVERT(nvarchar,right(GioHen,3)),Id_TC=" + hd.getId_TC() + ",NgayHen=N'" + XDate.toString(hd.getNgayHen(), "yyyy-MM-dd") + "' where Id=" + txtId_HD.getText();
                            String id = txtId_HD.getText();
                            String sql2 = "update HoaDon set GioKT=convert(nvarchar,(CONVERT(int,left(GioKT,2)+1)))+CONVERT(nvarchar,right(GioKT,3)) where Id =" + id;
                            try {
                                JDBCHelper.update(sql);
                                JDBCHelper.update(sql2);
                            } catch (Exception e) {
                            }
                            KiemTra(hd);
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } catch (Exception e) {
                }
            } catch (ParseException ex) {
                Logger.getLogger(DoiLich.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    public void KiemTra(HoaDon hd) {

        String sql4 = "select gioKT from HoaDon where Id =" + txtId_HD.getText();
        String sql5 = "select GioKT from HoaDon where id not like " + txtId_HD.getText();
        ResultSet rs5 = JDBCHelper.query(sql5);
        try {

            ResultSet rs4 = JDBCHelper.query(sql4);
            while (rs4.next()) {
                Object[] item1 = new Object[2];
                item1[0] = rs4.getString("GioKT");
                item1[1] = rs4.getString("NgayHen");
                String gioKT_ID = item1[0].toString();
                String ngayHen_ID = String.valueOf(XDate.toDate(item1[1].toString(), "yyyy-MM-dd"));

                List<Model.HoaDon> hd1 = hddao.selectGioKT(txtId_HD.getText());
                for (int i = hd1.size() - 1; i >= 0; i--) {
                    System.out.println("các phần tử trong list:" + hd1.get(i).getGioKetThuc());
                    if (gioKT_ID.equals(hd1.get(i).getGioKetThuc())) {
                        MsgBox.alert(this, "Giờ kết thúc trùng!");
                        String sql6 = "update HoaDon set GioHen=N'" + lblGioHen.getText() + "', GioKT=N'" + txtGioKT.getText() + "',Id_TC =" + txtMaTC.getText() + ",NgayHen=N'" + txtNgayHen.getText() + "' where Id=" + txtId_HD.getText();
                        try {
                            JDBCHelper.update(sql6);
                            MsgBox.alert(this, "Lấy lại giờ kết thúc và giờ hẹn");
                        } catch (Exception e) {
                        }
                        break;
                    }
                }
                break;

            }
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JComboBox<String> cboNgayDat;
    private javax.swing.JComboBox<String> cboThoCat;
    private javax.swing.JComboBox<String> cboThoiGian;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lblGioHen;
    private javax.swing.JTextField txtGioKT;
    private javax.swing.JTextField txtId_HD;
    private javax.swing.JTextField txtMaTC;
    private javax.swing.JTextField txtNgayHen;
    // End of variables declaration//GEN-END:variables
}
