/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ChucNang;

import Dao.KhachHangDAO;
import Dao.NhanVienDAO;
import Dao.QLTaiKhoanDAO;
import Dao.TaiKhoanDAO;
import Helper.MsgBox;
import UI.KhachHang1.KhachHangHome;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class QuenMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau
     */
    private final String alpha = "abcdefghijklmnopqrstuvwxyz";
    private final String digits = "0123456789";
    private final String ALPHA_NUMERIC = alpha + digits;
    int count = 8;
    private Random generator = new Random();
    TaiKhoanDAO tkdao = new TaiKhoanDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    QLTaiKhoanDAO khdao = new QLTaiKhoanDAO();
    String newPass = this.randomAlphaNumeric(count);
    int index = 0;

    public QuenMatKhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuiMK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboNV = new javax.swing.JRadioButton();
        cboND = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 141, 251));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(46, 125, 182));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/email.png"))); // NOI18N

        txtMail.setBackground(new java.awt.Color(46, 125, 182));
        txtMail.setForeground(new java.awt.Color(255, 255, 255));
        txtMail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMail)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUÊN MẬT KHẨU");

        btnGuiMK.setBackground(new java.awt.Color(255, 255, 255));
        btnGuiMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuiMK.setForeground(new java.awt.Color(0, 0, 255));
        btnGuiMK.setText("Gửi mật khẩu mới");
        btnGuiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMKActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nhập email của tài khoản :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bạn là :");

        buttonGroup1.add(cboNV);
        cboNV.setText("Nhân viên");

        buttonGroup1.add(cboND);
        cboND.setText("Người dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel2)
                .addGap(0, 157, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(cboNV, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGuiMK)
                                .addComponent(cboND, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnGuiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboNV)
                            .addComponent(cboND))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void btnGuiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMKActionPerformed
        check();
        if (index == 1) {
            guiMKMoi();
            try {
                tkdao.update(getTTTK());
                System.out.println("Pass là :" + getTTTK().getMatKhau());
            } catch (Exception e) {
                e.printStackTrace();
            }
            this.dispose();
            KhachHangHome main = new KhachHangHome();
            main.setVisible(true);
        }
    }//GEN-LAST:event_btnGuiMKActionPerformed

    Model.TaiKhoan getTTTK() {
        if (cboND.isSelected()) {
            int id = tkdao.getTenTKKH(txtMail.getText()).getId();
            String tenTK = tkdao.getTenTKKH(txtMail.getText()).getTenTK();
            String mk = newPass;
            int vaiTro = tkdao.getTenTKKH(txtMail.getText()).getVaiTro();
            String trangThai = tkdao.getTenTKKH(txtMail.getText()).getTrangThai();
            String hinh = tkdao.getTenTKKH(txtMail.getText()).getHinh();
            return new Model.TaiKhoan(id, tenTK, mk, vaiTro, trangThai, hinh);
        } else {
            int id = tkdao.getTenTKNV(txtMail.getText()).getId();
            String tenTK = tkdao.getTenTKNV(txtMail.getText()).getTenTK();
            String mk = newPass;
            int vaiTro = tkdao.getTenTKNV(txtMail.getText()).getVaiTro();
            String trangThai = tkdao.getTenTKNV(txtMail.getText()).getTrangThai();
            String hinh = tkdao.getTenTKNV(txtMail.getText()).getHinh();
            return new Model.TaiKhoan(id, tenTK, mk, vaiTro, trangThai, hinh);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau dialog = new QuenMatKhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    void check() {
        List<Model.NhanVien> listNV = nvdao.selectAll();
        List<Model.TTKhachHang> listKH = khdao.selectAll();
        String mail = txtMail.getText();

        if (txtMail.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền email");
            index = 0;
            return;
        }
        if (cboND.isSelected() == false && cboNV.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò");
            index = 0;
            return;
        }
        if (tkdao.getTenTKKH(mail) == null && tkdao.getTenTKNV(mail) == null) {
            JOptionPane.showMessageDialog(this, "Email không tồn tại");
            index = 0;
            return;
        }
        if (cboND.isSelected()) {
            for (Model.TTKhachHang x : listKH) {
                if (mail.equals(x.getEmail())) {
                    index = 1;
                    break;
                }
            }
            return;
        }
        if (cboNV.isSelected()) {
            for (Model.NhanVien x : listNV) {
                if (mail.equals(x.getEmail())) {
                    index = 1;
                    break;
                }
            }
            return;
        }
    }

    public void guiMKMoi() {
        try {
            String host = "smtp.gmail.com";
            String user = "trantuyetnhi185@gmail.com";
            String pass = "Maihuong123225";
            String to = txtMail.getText();
            String subject = "Reseting Code";
            String message = "Your new password is " + newPass;
            boolean sessionDebug = false;
            Properties props = System.getProperties();
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", "host");
            props.put("mail.smtp.port", "587");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.required", "true");
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session mailSession = Session.getDefaultInstance(props, null);
            mailSession.setDebug(sessionDebug);
            Message msg = new MimeMessage(mailSession);
            msg.setFrom(new InternetAddress(user));
            InternetAddress[] address = {new InternetAddress(to)};
            msg.setRecipients(Message.RecipientType.TO, address);
            msg.setSubject(subject);
            msg.setText(message);
            Transport transport = mailSession.getTransport("smtp");
            transport.connect(host, user, pass);
            transport.sendMessage(msg, msg.getAllRecipients());
            transport.close();
            MsgBox.alert(this, "Pass đã được gửi về email");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String randomAlphaNumeric(int count) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < count; i++) {
            int number = randomNumber(0, ALPHA_NUMERIC.length() - 1);
            char ch = ALPHA_NUMERIC.charAt(number);
            sb.append(ch);
        }
        return sb.toString();
    }

    public int randomNumber(int min, int max) {
        return generator.nextInt((max - min) + 1) + min;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cboND;
    private javax.swing.JRadioButton cboNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
}
